# Generated by Django 5.2 on 2025-04-29 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agronomist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agronomist',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='agronomist',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='agronomist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agronomist',
            name='expertise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agronomist',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agronomist',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crops_grown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
