# Generated by Django 5.2 on 2025-05-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_agronomist_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agronomist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agronomist',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='agronomist',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='agronomist',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='crops_grown',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='is_verified',
        ),
    ]
