# Generated by Django 5.2 on 2025-05-06 13:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agronomist_created_at_farmer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path),
        ),
        migrations.AddField(
            model_name='agronomist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agronomist',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path),
        ),
    ]
