# Generated by Django 5.2 on 2025-05-06 13:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agronomist_profile_picture_agronomist_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agronomist',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='agronomist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path, validators=[core.models.validate_image]),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path, validators=[core.models.validate_image]),
        ),
    ]
