# Generated by Django 5.2 on 2025-05-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agronomist_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agronomist',
            options={'verbose_name': 'Agronomist', 'verbose_name_plural': 'Agronomists'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
    ]
