# Generated by Django 5.2 on 2025-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_soiltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomist',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='farmer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu')], default='en', max_length=5),
        ),
    ]
