# Generated by Django 5.2 on 2025-05-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_agronomist_language_farmer_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agronomist',
            name='language',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='language',
        ),
    ]
