# Generated by Django 5.2 on 2025-05-30 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='helpful_by',
            field=models.ManyToManyField(blank=True, related_name='helpful_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommunityComment',
        ),
    ]
