# Generated by Django 5.2 on 2025-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agronomist', 'Agronomist')], default='farmer', max_length=20),
        ),
    ]
