# Generated by Django 5.2 on 2025-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu')], default='en', max_length=5),
        ),
    ]
