# Generated by Django 5.2 on 2025-05-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_language',
        ),
    ]
