# Generated by Django 5.2 on 2025-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu'), ('ig', 'Igbo'), ('fr', 'French')], default='en', max_length=5),
        ),
    ]
