# Generated by Django 5.2 on 2025-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu'), ('ig', 'Igbo')], default='en', max_length=5),
        ),
    ]
